#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 04/22/2018(m/d/y) 00:23:55 UTC from "Hardcore" data

desc = "Unique"

# Base type : settings pair
items = {
	"0 Abyssal Axe": {"base": "Abyssal Axe", "type": "unique very high"},
	"0 Assassin's Garb": {"base": "Assassin's Garb", "type": "unique very high"},
	"0 Atoll Map": {"base": "Atoll Map", "type": "unique very high"},
	"0 Bismuth Flask": {"base": "Bismuth Flask", "type": "unique very high"},
	"0 Bone Bow": {"base": "Bone Bow", "type": "unique very high"},
	"0 Bone Crypt Map": {"base": "Bone Crypt Map", "type": "unique very high"},
	"0 Branded Kite Shield": {"base": "Branded Kite Shield", "type": "unique very high"},
	"0 Carved Wand": {"base": "Carved Wand", "type": "unique very high"},
	"0 Cemetery Map": {"base": "Cemetery Map", "type": "unique very high"},
	"0 Close Helmet": {"base": "Close Helmet", "type": "unique very high"},
	"0 Coronal Leather": {"base": "Coronal Leather", "type": "unique very high"},
	"0 Corrugated Buckler": {"base": "Corrugated Buckler", "type": "unique very high"},
	"0 Crusader Gloves": {"base": "Crusader Gloves", "type": "unique very high"},
	"0 Crystal Wand": {"base": "Crystal Wand", "type": "unique very high"},
	"0 Deicide Mask": {"base": "Deicide Mask", "type": "unique very high"},
	"0 Desert Brigandine": {"base": "Desert Brigandine", "type": "unique very high"},
	"0 Dunes Map": {"base": "Dunes Map", "type": "unique very high"},
	"0 Etched Greatsword": {"base": "Etched Greatsword", "type": "unique very high"},
	"0 Ezomyte Burgonet": {"base": "Ezomyte Burgonet", "type": "unique very high"},
	"0 Gladiator Plate": {"base": "Gladiator Plate", "type": "unique very high"},
	"0 Gladius": {"base": "Gladius", "type": "unique very high"},
	"0 Grand Mana Flask": {"base": "Grand Mana Flask", "type": "unique very high"},
	"0 Granite Flask": {"base": "Granite Flask", "type": "unique very high"},
	"0 Great Crown": {"base": "Great Crown", "type": "unique very high"},
	"0 Harbinger Map": {"base": "Harbinger Map", "type": "unique very high"},
	"0 Hubris Circlet": {"base": "Hubris Circlet", "type": "unique very high"},
	"0 Imperial Claw": {"base": "Imperial Claw", "type": "unique very high"},
	"0 Lacquered Helmet": {"base": "Lacquered Helmet", "type": "unique very high"},
	"0 Leather Cap": {"base": "Leather Cap", "type": "unique very high"},
	"0 Lunaris Circlet": {"base": "Lunaris Circlet", "type": "unique very high"},
	"0 Meatgrinder": {"base": "Meatgrinder", "type": "unique very high"},
	"0 Midnight Blade": {"base": "Midnight Blade", "type": "unique very high"},
	"0 Mosaic Kite Shield": {"base": "Mosaic Kite Shield", "type": "unique very high"},
	"0 Necromancer Silks": {"base": "Necromancer Silks", "type": "unique very high"},
	"0 Necropolis Map": {"base": "Necropolis Map", "type": "unique very high"},
	"0 Overgrown Shrine Map": {"base": "Overgrown Shrine Map", "type": "unique very high"},
	"0 Prismatic Jewel": {"base": "Prismatic Jewel", "type": "unique very high"},
	"0 Prophecy Wand": {"base": "Prophecy Wand", "type": "unique very high"},
	"0 Ranger Bow": {"base": "Ranger Bow", "type": "unique very high"},
	"0 Raven Mask": {"base": "Raven Mask", "type": "unique very high"},
	"0 Rawhide Boots": {"base": "Rawhide Boots", "type": "unique very high"},
	"0 Rawhide Tower Shield": {"base": "Rawhide Tower Shield", "type": "unique very high"},
	"0 Reef Map": {"base": "Reef Map", "type": "unique very high"},
	"0 Sacrificial Garb": {"base": "Sacrificial Garb", "type": "unique very high"},
	"0 Saintly Chainmail": {"base": "Saintly Chainmail", "type": "unique very high"},
	"0 Sapphire Flask": {"base": "Sapphire Flask", "type": "unique very high"},
	"0 Secutor Helm": {"base": "Secutor Helm", "type": "unique very high"},
	"0 Shadow Axe": {"base": "Shadow Axe", "type": "unique very high"},
	"0 Siege Axe": {"base": "Siege Axe", "type": "unique very high"},
	"0 Sinner Tricorne": {"base": "Sinner Tricorne", "type": "unique very high"},
	"0 Slaughter Knife": {"base": "Slaughter Knife", "type": "unique very high"},
	"0 Slink Boots": {"base": "Slink Boots", "type": "unique very high"},
	"0 Soldier Gloves": {"base": "Soldier Gloves", "type": "unique very high"},
	"0 Sorcerer Boots": {"base": "Sorcerer Boots", "type": "unique very high"},
	"0 Steel Gauntlets": {"base": "Steel Gauntlets", "type": "unique very high"},
	"0 Stibnite Flask": {"base": "Stibnite Flask", "type": "unique very high"},
	"0 Strand Map": {"base": "Strand Map", "type": "unique very high"},
	"0 Terror Claw": {"base": "Terror Claw", "type": "unique very high"},
	"0 Two-Stone Ring": {"base": "Two-Stone Ring", "type": "unique very high"},
	"0 Underground River Map": {"base": "Underground River Map", "type": "unique very high"},
	"0 Vaal Axe": {"base": "Vaal Axe", "type": "unique very high"},
	"0 Vaal Mask": {"base": "Vaal Mask", "type": "unique very high"},
	"0 Vaal Sceptre": {"base": "Vaal Sceptre", "type": "unique very high"},
	"0 Velvet Slippers": {"base": "Velvet Slippers", "type": "unique very high"},
	"0 Widowsilk Robe": {"base": "Widowsilk Robe", "type": "unique very high"},
	"1 Amber Amulet": {"base": "Amber Amulet", "type": "unique high"},
	"1 Ambusher": {"base": "Ambusher", "type": "unique high"},
	"1 Amethyst Flask": {"base": "Amethyst Flask", "type": "unique high"},
	"1 Archon Kite Shield": {"base": "Archon Kite Shield", "type": "unique high"},
	"1 Assassin's Mitts": {"base": "Assassin's Mitts", "type": "unique high"},
	"1 Baroque Round Shield": {"base": "Baroque Round Shield", "type": "unique high"},
	"1 Bone Armour": {"base": "Bone Armour", "type": "unique high"},
	"1 Boot Blade": {"base": "Boot Blade", "type": "unique high"},
	"1 Bronze Gauntlets": {"base": "Bronze Gauntlets", "type": "unique high"},
	"1 Carnal Armour": {"base": "Carnal Armour", "type": "unique high"},
	"1 Carnal Mitts": {"base": "Carnal Mitts", "type": "unique high"},
	"1 Coiled Staff": {"base": "Coiled Staff", "type": "unique high"},
	"1 Colossal Tower Shield": {"base": "Colossal Tower Shield", "type": "unique high"},
	"1 Conjurer Boots": {"base": "Conjurer Boots", "type": "unique high"},
	"1 Conquest Chainmail": {"base": "Conquest Chainmail", "type": "unique high"},
	"1 Crusader Plate": {"base": "Crusader Plate", "type": "unique high"},
	"1 Cutthroat's Garb": {"base": "Cutthroat's Garb", "type": "unique high"},
	"1 Decorative Axe": {"base": "Decorative Axe", "type": "unique high"},
	"1 Destiny Leather": {"base": "Destiny Leather", "type": "unique high"},
	"1 Diamond Ring": {"base": "Diamond Ring", "type": "unique high"},
	"1 Enameled Buckler": {"base": "Enameled Buckler", "type": "unique high"},
	"1 Eternal Sword": {"base": "Eternal Sword", "type": "unique high"},
	"1 Ezomyte Staff": {"base": "Ezomyte Staff", "type": "unique high"},
	"1 Goathide Boots": {"base": "Goathide Boots", "type": "unique high"},
	"1 Gold Ring": {"base": "Gold Ring", "type": "unique high"},
	"1 Golden Plate": {"base": "Golden Plate", "type": "unique high"},
	"1 Great Mallet": {"base": "Great Mallet", "type": "unique high"},
	"1 Harbinger Bow": {"base": "Harbinger Bow", "type": "unique high"},
	"1 Headsman Axe": {"base": "Headsman Axe", "type": "unique high"},
	"1 Imperial Staff": {"base": "Imperial Staff", "type": "unique high"},
	"1 Infernal Sword": {"base": "Infernal Sword", "type": "unique high"},
	"1 Ironscale Boots": {"base": "Ironscale Boots", "type": "unique high"},
	"1 Karui Maul": {"base": "Karui Maul", "type": "unique high"},
	"1 Laminated Kite Shield": {"base": "Laminated Kite Shield", "type": "unique high"},
	"1 Lapis Amulet": {"base": "Lapis Amulet", "type": "unique high"},
	"1 Large Hybrid Flask": {"base": "Large Hybrid Flask", "type": "unique high"},
	"1 Lion Pelt": {"base": "Lion Pelt", "type": "unique high"},
	"1 Lion Sword": {"base": "Lion Sword", "type": "unique high"},
	"1 Mirrored Spiked Shield": {"base": "Mirrored Spiked Shield", "type": "unique high"},
	"1 Murder Mitts": {"base": "Murder Mitts", "type": "unique high"},
	"1 Nightmare Bascinet": {"base": "Nightmare Bascinet", "type": "unique high"},
	"1 Opal Wand": {"base": "Opal Wand", "type": "unique high"},
	"1 Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "type": "unique high"},
	"1 Pinnacle Tower Shield": {"base": "Pinnacle Tower Shield", "type": "unique high"},
	"1 Praetor Crown": {"base": "Praetor Crown", "type": "unique high"},
	"1 Quicksilver Flask": {"base": "Quicksilver Flask", "type": "unique high"},
	"1 Reaver Sword": {"base": "Reaver Sword", "type": "unique high"},
	"1 Reinforced Tower Shield": {"base": "Reinforced Tower Shield", "type": "unique high"},
	"1 Rock Breaker": {"base": "Rock Breaker", "type": "unique high"},
	"1 Ruby Flask": {"base": "Ruby Flask", "type": "unique high"},
	"1 Sadist Garb": {"base": "Sadist Garb", "type": "unique high"},
	"1 Samite Gloves": {"base": "Samite Gloves", "type": "unique high"},
	"1 Sapphire Ring": {"base": "Sapphire Ring", "type": "unique high"},
	"1 Savant's Robe": {"base": "Savant's Robe", "type": "unique high"},
	"1 Serpentscale Boots": {"base": "Serpentscale Boots", "type": "unique high"},
	"1 Silver Flask": {"base": "Silver Flask", "type": "unique high"},
	"1 Soldier Boots": {"base": "Soldier Boots", "type": "unique high"},
	"1 Spidersilk Robe": {"base": "Spidersilk Robe", "type": "unique high"},
	"1 Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "type": "unique high"},
	"1 Spine Bow": {"base": "Spine Bow", "type": "unique high"},
	"1 Spiraled Wand": {"base": "Spiraled Wand", "type": "unique high"},
	"1 Steelscale Gauntlets": {"base": "Steelscale Gauntlets", "type": "unique high"},
	"1 Strapped Mitts": {"base": "Strapped Mitts", "type": "unique high"},
	"1 Sulphur Flask": {"base": "Sulphur Flask", "type": "unique high"},
	"1 Supreme Spiked Shield": {"base": "Supreme Spiked Shield", "type": "unique high"},
	"1 Terror Maul": {"base": "Terror Maul", "type": "unique high"},
	"1 Thorium Spirit Shield": {"base": "Thorium Spirit Shield", "type": "unique high"},
	"1 Throat Stabber": {"base": "Throat Stabber", "type": "unique high"},
	"1 Titan Gauntlets": {"base": "Titan Gauntlets", "type": "unique high"},
	"1 Titanium Spirit Shield": {"base": "Titanium Spirit Shield", "type": "unique high"},
	"1 Tornado Wand": {"base": "Tornado Wand", "type": "unique high"},
	"1 Triumphant Lamellar": {"base": "Triumphant Lamellar", "type": "unique high"},
	"1 Unset Ring": {"base": "Unset Ring", "type": "unique high"},
	"1 Ursine Pelt": {"base": "Ursine Pelt", "type": "unique high"},
	"1 Vaal Blade": {"base": "Vaal Blade", "type": "unique high"},
	"1 Vaal Regalia": {"base": "Vaal Regalia", "type": "unique high"},
	"1 Vile Staff": {"base": "Vile Staff", "type": "unique high"},
	"1 Zodiac Leather": {"base": "Zodiac Leather", "type": "unique high"},
	"6 Agate Amulet": {"base": "Agate Amulet", "type": "unique special"},
	"6 Chain Belt": {"base": "Chain Belt", "type": "unique special"},
	"6 Cloth Belt": {"base": "Cloth Belt", "type": "unique special"},
	"6 Cobalt Jewel": {"base": "Cobalt Jewel", "type": "unique special"},
	"6 Coral Ring": {"base": "Coral Ring", "type": "unique special"},
	"6 Crimson Jewel": {"base": "Crimson Jewel", "type": "unique special"},
	"6 Fire Arrow Quiver": {"base": "Fire Arrow Quiver", "type": "unique special"},
	"6 Gilded Sallet": {"base": "Gilded Sallet", "type": "unique special"},
	"6 Gold Amulet": {"base": "Gold Amulet", "type": "unique special"},
	"6 Heavy Belt": {"base": "Heavy Belt", "type": "unique special"},
	"6 Iron Ring": {"base": "Iron Ring", "type": "unique special"},
	"6 Leather Belt": {"base": "Leather Belt", "type": "unique special"},
	"6 Moonstone Ring": {"base": "Moonstone Ring", "type": "unique special"},
	"6 Onyx Amulet": {"base": "Onyx Amulet", "type": "unique special"},
	"6 Paua Ring": {"base": "Paua Ring", "type": "unique special"},
	"6 Plate Vest": {"base": "Plate Vest", "type": "unique special"},
	"6 Prismatic Ring": {"base": "Prismatic Ring", "type": "unique special"},
	"6 Ruby Ring": {"base": "Ruby Ring", "type": "unique special"},
	"6 Turquoise Amulet": {"base": "Turquoise Amulet", "type": "unique special"},
	"6 Two-Point Arrow Quiver": {"base": "Two-Point Arrow Quiver", "type": "unique special"},
	"6 Viridian Jewel": {"base": "Viridian Jewel", "type": "unique special"},
	"6 War Hammer": {"base": "War Hammer", "type": "unique special"},
	"7 Blinder": {"base": "Blinder", "type": "unique low"},
	"7 Copper Plate": {"base": "Copper Plate", "type": "unique low"},
	"7 Crude Bow": {"base": "Crude Bow", "type": "unique low"},
	"7 Demon's Horn": {"base": "Demon's Horn", "type": "unique low"},
	"7 Dream Mace": {"base": "Dream Mace", "type": "unique low"},
	"7 Festival Mask": {"base": "Festival Mask", "type": "unique low"},
	"7 Gnarled Branch": {"base": "Gnarled Branch", "type": "unique low"},
	"7 Golden Mask": {"base": "Golden Mask", "type": "unique low"},
	"7 Holy Chainmail": {"base": "Holy Chainmail", "type": "unique low"},
	"7 Jade Hatchet": {"base": "Jade Hatchet", "type": "unique low"},
	"7 Nailed Fist": {"base": "Nailed Fist", "type": "unique low"},
	"7 Scholar's Robe": {"base": "Scholar's Robe", "type": "unique low"},
	"7 Sentinel Jacket": {"base": "Sentinel Jacket", "type": "unique low"},
	"7 Shadow Sceptre": {"base": "Shadow Sceptre", "type": "unique low"},
	"7 Silk Gloves": {"base": "Silk Gloves", "type": "unique low"},
	"7 Simple Robe": {"base": "Simple Robe", "type": "unique low"},
	"7 Spiked Club": {"base": "Spiked Club", "type": "unique low"},
	"7 Stiletto": {"base": "Stiletto", "type": "unique low"},
	"7 Thresher Claw": {"base": "Thresher Claw", "type": "unique low"},
	"7 Timeworn Claw": {"base": "Timeworn Claw", "type": "unique low"},
	"7 Visored Sallet": {"base": "Visored Sallet", "type": "unique low"},
	"7 War Buckler": {"base": "War Buckler", "type": "unique low"},
	"7 Woodsplitter": {"base": "Woodsplitter", "type": "unique low"},
	"9 Other uniques": {"type": "unique normal"}
}
