#!/usr/bin/python
# -*- coding: utf-8 -*-
# Created: 04/09/2018(m/d/y) 03:01:46 UTC from "Hardcore" data

desc = "Unique"

# Base type : settings pair
items = {
	"0 Amethyst Flask": {"base": "Amethyst Flask", "type": "unique very high"},
	"0 Assassin's Garb": {"base": "Assassin's Garb", "type": "unique very high"},
	"0 Assassin's Mitts": {"base": "Assassin's Mitts", "type": "unique very high"},
	"0 Chateau Map": {"base": "Chateau Map", "type": "unique very high"},
	"0 Coronal Leather": {"base": "Coronal Leather", "type": "unique very high"},
	"0 Courtyard Map": {"base": "Courtyard Map", "type": "unique very high"},
	"0 Crusader Gloves": {"base": "Crusader Gloves", "type": "unique very high"},
	"0 Elegant Foil": {"base": "Elegant Foil", "type": "unique very high"},
	"0 Exquisite Leather": {"base": "Exquisite Leather", "type": "unique very high"},
	"0 Ezomyte Tower Shield": {"base": "Ezomyte Tower Shield", "type": "unique very high"},
	"0 Full Wyrmscale": {"base": "Full Wyrmscale", "type": "unique very high"},
	"0 Golden Bracers": {"base": "Golden Bracers", "type": "unique very high"},
	"0 Golden Mantle": {"base": "Golden Mantle", "type": "unique very high"},
	"0 Golden Mask": {"base": "Golden Mask", "type": "unique very high"},
	"0 Golden Obi": {"base": "Golden Obi", "type": "unique very high"},
	"0 Grand Mana Flask": {"base": "Grand Mana Flask", "type": "unique very high"},
	"0 Granite Flask": {"base": "Granite Flask", "type": "unique very high"},
	"0 Hellion's Paw": {"base": "Hellion's Paw", "type": "unique very high"},
	"0 Hubris Circlet": {"base": "Hubris Circlet", "type": "unique very high"},
	"0 Imperial Skean": {"base": "Imperial Skean", "type": "unique very high"},
	"0 Iron Sceptre": {"base": "Iron Sceptre", "type": "unique very high"},
	"0 Judgement Staff": {"base": "Judgement Staff", "type": "unique very high"},
	"0 Large Hybrid Flask": {"base": "Large Hybrid Flask", "type": "unique very high"},
	"0 Leather Cap": {"base": "Leather Cap", "type": "unique very high"},
	"0 Leather Hood": {"base": "Leather Hood", "type": "unique very high"},
	"0 Lion Sword": {"base": "Lion Sword", "type": "unique very high"},
	"0 Midnight Blade": {"base": "Midnight Blade", "type": "unique very high"},
	"0 Murder Boots": {"base": "Murder Boots", "type": "unique very high"},
	"0 Necromancer Silks": {"base": "Necromancer Silks", "type": "unique very high"},
	"0 Opal Wand": {"base": "Opal Wand", "type": "unique very high"},
	"0 Pinnacle Tower Shield": {"base": "Pinnacle Tower Shield", "type": "unique very high"},
	"0 Prismatic Jewel": {"base": "Prismatic Jewel", "type": "unique very high"},
	"0 Rawhide Boots": {"base": "Rawhide Boots", "type": "unique very high"},
	"0 Rawhide Tower Shield": {"base": "Rawhide Tower Shield", "type": "unique very high"},
	"0 Ritual Sceptre": {"base": "Ritual Sceptre", "type": "unique very high"},
	"0 Sapphire Flask": {"base": "Sapphire Flask", "type": "unique very high"},
	"0 Savant's Robe": {"base": "Savant's Robe", "type": "unique very high"},
	"0 Sharkskin Boots": {"base": "Sharkskin Boots", "type": "unique very high"},
	"0 Siege Axe": {"base": "Siege Axe", "type": "unique very high"},
	"0 Silver Flask": {"base": "Silver Flask", "type": "unique very high"},
	"0 Sorcerer Boots": {"base": "Sorcerer Boots", "type": "unique very high"},
	"0 Steelscale Gauntlets": {"base": "Steelscale Gauntlets", "type": "unique very high"},
	"0 Stygian Vise": {"base": "Stygian Vise", "type": "unique very high"},
	"0 Topaz Flask": {"base": "Topaz Flask", "type": "unique very high"},
	"0 Twilight Blade": {"base": "Twilight Blade", "type": "unique very high"},
	"0 Two-Stone Ring": {"base": "Two-Stone Ring", "type": "unique very high"},
	"0 Vaal Blade": {"base": "Vaal Blade", "type": "unique very high"},
	"0 Varnished Coat": {"base": "Varnished Coat", "type": "unique very high"},
	"0 Wereclaw Talisman": {"base": "Wereclaw Talisman", "type": "unique very high"},
	"1 Abyssal Axe": {"base": "Abyssal Axe", "type": "unique high"},
	"1 Ancient Gauntlets": {"base": "Ancient Gauntlets", "type": "unique high"},
	"1 Assassin Bow": {"base": "Assassin Bow", "type": "unique high"},
	"1 Astral Plate": {"base": "Astral Plate", "type": "unique high"},
	"1 Atoll Map": {"base": "Atoll Map", "type": "unique high"},
	"1 Aventail Helmet": {"base": "Aventail Helmet", "type": "unique high"},
	"1 Bone Armour": {"base": "Bone Armour", "type": "unique high"},
	"1 Bone Circlet": {"base": "Bone Circlet", "type": "unique high"},
	"1 Bone Crypt Map": {"base": "Bone Crypt Map", "type": "unique high"},
	"1 Branded Kite Shield": {"base": "Branded Kite Shield", "type": "unique high"},
	"1 Bronze Gauntlets": {"base": "Bronze Gauntlets", "type": "unique high"},
	"1 Carnal Armour": {"base": "Carnal Armour", "type": "unique high"},
	"1 Carnal Mitts": {"base": "Carnal Mitts", "type": "unique high"},
	"1 Chain Gloves": {"base": "Chain Gloves", "type": "unique high"},
	"1 Coiled Staff": {"base": "Coiled Staff", "type": "unique high"},
	"1 Conjurer Boots": {"base": "Conjurer Boots", "type": "unique high"},
	"1 Conjurer Gloves": {"base": "Conjurer Gloves", "type": "unique high"},
	"1 Crusader Plate": {"base": "Crusader Plate", "type": "unique high"},
	"1 Crystal Sceptre": {"base": "Crystal Sceptre", "type": "unique high"},
	"1 Cursed Crypt Map": {"base": "Cursed Crypt Map", "type": "unique high"},
	"1 Desert Brigandine": {"base": "Desert Brigandine", "type": "unique high"},
	"1 Destiny Leather": {"base": "Destiny Leather", "type": "unique high"},
	"1 Destroyer Regalia": {"base": "Destroyer Regalia", "type": "unique high"},
	"1 Ebony Tower Shield": {"base": "Ebony Tower Shield", "type": "unique high"},
	"1 Elegant Ringmail": {"base": "Elegant Ringmail", "type": "unique high"},
	"1 Engraved Wand": {"base": "Engraved Wand", "type": "unique high"},
	"1 Etched Greatsword": {"base": "Etched Greatsword", "type": "unique high"},
	"1 Eternal Sword": {"base": "Eternal Sword", "type": "unique high"},
	"1 Ezomyte Blade": {"base": "Ezomyte Blade", "type": "unique high"},
	"1 Ezomyte Burgonet": {"base": "Ezomyte Burgonet", "type": "unique high"},
	"1 Ezomyte Staff": {"base": "Ezomyte Staff", "type": "unique high"},
	"1 Fiend Dagger": {"base": "Fiend Dagger", "type": "unique high"},
	"1 Fright Claw": {"base": "Fright Claw", "type": "unique high"},
	"1 Gavel": {"base": "Gavel", "type": "unique high"},
	"1 Goathide Boots": {"base": "Goathide Boots", "type": "unique high"},
	"1 Gold Ring": {"base": "Gold Ring", "type": "unique high"},
	"1 Great Mallet": {"base": "Great Mallet", "type": "unique high"},
	"1 Harbinger Bow": {"base": "Harbinger Bow", "type": "unique high"},
	"1 Headsman Axe": {"base": "Headsman Axe", "type": "unique high"},
	"1 Imbued Wand": {"base": "Imbued Wand", "type": "unique high"},
	"1 Imperial Claw": {"base": "Imperial Claw", "type": "unique high"},
	"1 Imperial Staff": {"base": "Imperial Staff", "type": "unique high"},
	"1 Ironscale Boots": {"base": "Ironscale Boots", "type": "unique high"},
	"1 Karui Chopper": {"base": "Karui Chopper", "type": "unique high"},
	"1 Lacquered Garb": {"base": "Lacquered Garb", "type": "unique high"},
	"1 Lathi": {"base": "Lathi", "type": "unique high"},
	"1 Latticed Ringmail": {"base": "Latticed Ringmail", "type": "unique high"},
	"1 Leather Belt": {"base": "Leather Belt", "type": "unique high"},
	"1 Legion Sword": {"base": "Legion Sword", "type": "unique high"},
	"1 Long Staff": {"base": "Long Staff", "type": "unique high"},
	"1 Marble Amulet": {"base": "Marble Amulet", "type": "unique high"},
	"1 Meatgrinder": {"base": "Meatgrinder", "type": "unique high"},
	"1 Mind Cage": {"base": "Mind Cage", "type": "unique high"},
	"1 Necropolis Map": {"base": "Necropolis Map", "type": "unique high"},
	"1 Nightmare Bascinet": {"base": "Nightmare Bascinet", "type": "unique high"},
	"1 Opal Sceptre": {"base": "Opal Sceptre", "type": "unique high"},
	"1 Ornate Mace": {"base": "Ornate Mace", "type": "unique high"},
	"1 Ornate Sword": {"base": "Ornate Sword", "type": "unique high"},
	"1 Overgrown Shrine Map": {"base": "Overgrown Shrine Map", "type": "unique high"},
	"1 Penetrating Arrow Quiver": {"base": "Penetrating Arrow Quiver", "type": "unique high"},
	"1 Praetor Crown": {"base": "Praetor Crown", "type": "unique high"},
	"1 Primordial Staff": {"base": "Primordial Staff", "type": "unique high"},
	"1 Promenade Map": {"base": "Promenade Map", "type": "unique high"},
	"1 Quartz Flask": {"base": "Quartz Flask", "type": "unique high"},
	"1 Quicksilver Flask": {"base": "Quicksilver Flask", "type": "unique high"},
	"1 Reef Map": {"base": "Reef Map", "type": "unique high"},
	"1 Reinforced Greaves": {"base": "Reinforced Greaves", "type": "unique high"},
	"1 Rock Breaker": {"base": "Rock Breaker", "type": "unique high"},
	"1 Ruby Flask": {"base": "Ruby Flask", "type": "unique high"},
	"1 Rustic Sash": {"base": "Rustic Sash", "type": "unique high"},
	"1 Sage Wand": {"base": "Sage Wand", "type": "unique high"},
	"1 Samite Gloves": {"base": "Samite Gloves", "type": "unique high"},
	"1 Samite Helmet": {"base": "Samite Helmet", "type": "unique high"},
	"1 Sapphire Ring": {"base": "Sapphire Ring", "type": "unique high"},
	"1 Scholar Boots": {"base": "Scholar Boots", "type": "unique high"},
	"1 Serpentine Staff": {"base": "Serpentine Staff", "type": "unique high"},
	"1 Serpentscale Boots": {"base": "Serpentscale Boots", "type": "unique high"},
	"1 Serpentscale Gauntlets": {"base": "Serpentscale Gauntlets", "type": "unique high"},
	"1 Silk Gloves": {"base": "Silk Gloves", "type": "unique high"},
	"1 Sinner Tricorne": {"base": "Sinner Tricorne", "type": "unique high"},
	"1 Slaughter Knife": {"base": "Slaughter Knife", "type": "unique high"},
	"1 Slink Boots": {"base": "Slink Boots", "type": "unique high"},
	"1 Spidersilk Robe": {"base": "Spidersilk Robe", "type": "unique high"},
	"1 Spike-Point Arrow Quiver": {"base": "Spike-Point Arrow Quiver", "type": "unique high"},
	"1 Spine Bow": {"base": "Spine Bow", "type": "unique high"},
	"1 Steel Gauntlets": {"base": "Steel Gauntlets", "type": "unique high"},
	"1 Stibnite Flask": {"base": "Stibnite Flask", "type": "unique high"},
	"1 Strapped Mitts": {"base": "Strapped Mitts", "type": "unique high"},
	"1 Sundering Axe": {"base": "Sundering Axe", "type": "unique high"},
	"1 Supreme Spiked Shield": {"base": "Supreme Spiked Shield", "type": "unique high"},
	"1 Terror Claw": {"base": "Terror Claw", "type": "unique high"},
	"1 Throat Stabber": {"base": "Throat Stabber", "type": "unique high"},
	"1 Tiger Sword": {"base": "Tiger Sword", "type": "unique high"},
	"1 Titan Gauntlets": {"base": "Titan Gauntlets", "type": "unique high"},
	"1 Tornado Wand": {"base": "Tornado Wand", "type": "unique high"},
	"1 Trapper Boots": {"base": "Trapper Boots", "type": "unique high"},
	"1 Turquoise Amulet": {"base": "Turquoise Amulet", "type": "unique high"},
	"1 Underground River Map": {"base": "Underground River Map", "type": "unique high"},
	"1 Ursine Pelt": {"base": "Ursine Pelt", "type": "unique high"},
	"1 Vaal Axe": {"base": "Vaal Axe", "type": "unique high"},
	"1 Vaal Regalia": {"base": "Vaal Regalia", "type": "unique high"},
	"1 Vaal Sceptre": {"base": "Vaal Sceptre", "type": "unique high"},
	"1 Vine Circlet": {"base": "Vine Circlet", "type": "unique high"},
	"1 Visored Sallet": {"base": "Visored Sallet", "type": "unique high"},
	"1 Void Sceptre": {"base": "Void Sceptre", "type": "unique high"},
	"6 Chain Belt": {"base": "Chain Belt", "type": "unique special"},
	"6 Clasped Boots": {"base": "Clasped Boots", "type": "unique special"},
	"6 Cloth Belt": {"base": "Cloth Belt", "type": "unique special"},
	"6 Cobalt Jewel": {"base": "Cobalt Jewel", "type": "unique special"},
	"6 Coral Amulet": {"base": "Coral Amulet", "type": "unique special"},
	"6 Coral Ring": {"base": "Coral Ring", "type": "unique special"},
	"6 Crimson Jewel": {"base": "Crimson Jewel", "type": "unique special"},
	"6 Crude Bow": {"base": "Crude Bow", "type": "unique special"},
	"6 Diamond Ring": {"base": "Diamond Ring", "type": "unique special"},
	"6 Elegant Sword": {"base": "Elegant Sword", "type": "unique special"},
	"6 Gold Amulet": {"base": "Gold Amulet", "type": "unique special"},
	"6 Heavy Belt": {"base": "Heavy Belt", "type": "unique special"},
	"6 Iron Ring": {"base": "Iron Ring", "type": "unique special"},
	"6 Jade Amulet": {"base": "Jade Amulet", "type": "unique special"},
	"6 Jade Hatchet": {"base": "Jade Hatchet", "type": "unique special"},
	"6 Lapis Amulet": {"base": "Lapis Amulet", "type": "unique special"},
	"6 Moonstone Ring": {"base": "Moonstone Ring", "type": "unique special"},
	"6 Onyx Amulet": {"base": "Onyx Amulet", "type": "unique special"},
	"6 Paua Ring": {"base": "Paua Ring", "type": "unique special"},
	"6 Prophet Crown": {"base": "Prophet Crown", "type": "unique special"},
	"6 Sledgehammer": {"base": "Sledgehammer", "type": "unique special"},
	"6 Unset Ring": {"base": "Unset Ring", "type": "unique special"},
	"6 Viridian Jewel": {"base": "Viridian Jewel", "type": "unique special"},
	"6 War Hammer": {"base": "War Hammer", "type": "unique special"},
	"6 Woodsplitter": {"base": "Woodsplitter", "type": "unique special"},
	"7 Bastard Sword": {"base": "Bastard Sword", "type": "unique low"},
	"7 Bronze Sceptre": {"base": "Bronze Sceptre", "type": "unique low"},
	"7 Buckskin Tunic": {"base": "Buckskin Tunic", "type": "unique low"},
	"7 Carved Wand": {"base": "Carved Wand", "type": "unique low"},
	"7 Decimation Bow": {"base": "Decimation Bow", "type": "unique low"},
	"7 Deerskin Boots": {"base": "Deerskin Boots", "type": "unique low"},
	"7 Driftwood Wand": {"base": "Driftwood Wand", "type": "unique low"},
	"7 Gnarled Branch": {"base": "Gnarled Branch", "type": "unique low"},
	"7 Goathide Gloves": {"base": "Goathide Gloves", "type": "unique low"},
	"7 Iron Circlet": {"base": "Iron Circlet", "type": "unique low"},
	"7 Iron Mask": {"base": "Iron Mask", "type": "unique low"},
	"7 Iron Staff": {"base": "Iron Staff", "type": "unique low"},
	"7 Mosaic Kite Shield": {"base": "Mosaic Kite Shield", "type": "unique low"},
	"7 Nailed Fist": {"base": "Nailed Fist", "type": "unique low"},
	"7 Platinum Kris": {"base": "Platinum Kris", "type": "unique low"},
	"7 Recurve Bow": {"base": "Recurve Bow", "type": "unique low"},
	"7 Rotted Round Shield": {"base": "Rotted Round Shield", "type": "unique low"},
	"7 Rusted Sword": {"base": "Rusted Sword", "type": "unique low"},
	"7 Scholar's Robe": {"base": "Scholar's Robe", "type": "unique low"},
	"7 Simple Robe": {"base": "Simple Robe", "type": "unique low"},
	"7 Skinning Knife": {"base": "Skinning Knife", "type": "unique low"},
	"7 Stealth Boots": {"base": "Stealth Boots", "type": "unique low"},
	"7 Stiletto": {"base": "Stiletto", "type": "unique low"},
	"7 Strapped Boots": {"base": "Strapped Boots", "type": "unique low"},
	"7 Strapped Leather": {"base": "Strapped Leather", "type": "unique low"},
	"7 Studded Belt": {"base": "Studded Belt", "type": "unique low"},
	"7 Velvet Slippers": {"base": "Velvet Slippers", "type": "unique low"},
	"7 Wool Gloves": {"base": "Wool Gloves", "type": "unique low"},
	"7 Wrapped Mitts": {"base": "Wrapped Mitts", "type": "unique low"},
	"9 Other uniques": {"type": "unique normal"}
}
